# This is a basic workflow to help you get started with Actions

name: Cordova GitHub CI #

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Force XCode 11.3
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app

      - name: Setup NodeJS 14
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Install cordova
        run: npm install cordova@10 -g

      - name: Build
        run: cordova create myApp org.apache.cordova.myApp myApp; cd myApp; \
          cordova platform add ios@latest --verbose \
          cordova plugin add ../ --verbose \
          cordova build ios --verbose
